# Generated by Django 2.1.2 on 2018-12-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Char',
            new_name='Article',
        ),
    ]
