# Generated by Django 2.1.2 on 2018-12-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0002_auto_20181219_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='var.png', upload_to=''),
        ),
    ]
